package com.redbus.bean.pojo;
// Generated Jun 22, 2024 7:50:33 PM by Hibernate Tools 3.4.0.CR1


import java.sql.Date;
import java.sql.Timestamp;

/**
 * BookingsData generated by hbm2java
 */
public class BookingsData  implements java.io.Serializable {


     private Long bookingId;
     private Date bookingDate;
     private String gender;
     private Integer totalPrice;
     private String seats;
     private String isActive;
     private Long modifiedBy;
     private Date modifiedAt;
     private Long createdBy;
     private Timestamp createdAt;
     private Bus bus;
     private User user;
     private BoardingPoint boardingPoint;
     private DroppingPoint droppingPoint;

    public BookingsData() {
    }

	
    public BookingsData(Date bookingDate, String gender, Integer totalPrice, String seats, String isActive, Long createdBy, Timestamp createdAt) {
        this.bookingDate = bookingDate;
        this.gender = gender;
        this.totalPrice = totalPrice;
        this.seats = seats;
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }
    public BookingsData(Date bookingDate, String gender, Integer totalPrice, String seats, String isActive, Long modifiedBy, Date modifiedAt, Long createdBy, Timestamp createdAt, Bus bus, User user, BoardingPoint boardingPoint, DroppingPoint droppingPoint) {
       this.bookingDate = bookingDate;
       this.gender = gender;
       this.totalPrice = totalPrice;
       this.seats = seats;
       this.isActive = isActive;
       this.modifiedBy = modifiedBy;
       this.modifiedAt = modifiedAt;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.bus = bus;
       this.user = user;
       this.boardingPoint = boardingPoint;
       this.droppingPoint = droppingPoint;
    }
   
    public Long getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(Long bookingId) {
        this.bookingId = bookingId;
    }
    public Date getBookingDate() {
        return this.bookingDate;
    }
    
    public void setBookingDate(Date bookingDate) {
        this.bookingDate = bookingDate;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Integer getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getSeats() {
        return this.seats;
    }
    
    public void setSeats(String seats) {
        this.seats = seats;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Long getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedAt() {
        return this.modifiedAt;
    }
    
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public BoardingPoint getBoardingPoint() {
        return this.boardingPoint;
    }
    
    public void setBoardingPoint(BoardingPoint boardingPoint) {
        this.boardingPoint = boardingPoint;
    }
    public DroppingPoint getDroppingPoint() {
        return this.droppingPoint;
    }
    
    public void setDroppingPoint(DroppingPoint droppingPoint) {
        this.droppingPoint = droppingPoint;
    }




}


