package com.redbus.bean.pojo;
// Generated Jun 22, 2024 7:50:33 PM by Hibernate Tools 3.4.0.CR1


import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus  implements java.io.Serializable {


     private Long busId;
     private String busName;
     private String route;
     private String busFrom;
     private String busTo;
     private Time startTime;
     private Time endTime;
     private String isActive;
     private Long modifiedBy;
     private Date modifiedAt;
     private Long createdBy;
     private Timestamp createdAt;
     private Set busInfos = new HashSet(0);
     private Set bookingsDatas = new HashSet(0);
     private Set boardingPoints = new HashSet(0);
     private Set droppingPoints = new HashSet(0);
     private Set busesImages = new HashSet(0);

    public Bus() {
    }

	
    public Bus(String busName, String route, String busFrom, String busTo, Time startTime, Time endTime, String isActive, Timestamp createdAt) {
        this.busName = busName;
        this.route = route;
        this.busFrom = busFrom;
        this.busTo = busTo;
        this.startTime = startTime;
        this.endTime = endTime;
        this.isActive = isActive;
        this.createdAt = createdAt;
    }
    public Bus(String busName, String route, String busFrom, String busTo, Time startTime, Time endTime, String isActive, Long modifiedBy, Date modifiedAt, Long createdBy, Timestamp createdAt, Set busInfos, Set bookingsDatas, Set boardingPoints, Set droppingPoints, Set busesImages) {
       this.busName = busName;
       this.route = route;
       this.busFrom = busFrom;
       this.busTo = busTo;
       this.startTime = startTime;
       this.endTime = endTime;
       this.isActive = isActive;
       this.modifiedBy = modifiedBy;
       this.modifiedAt = modifiedAt;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.busInfos = busInfos;
       this.bookingsDatas = bookingsDatas;
       this.boardingPoints = boardingPoints;
       this.droppingPoints = droppingPoints;
       this.busesImages = busesImages;
    }
   
    public Long getBusId() {
        return this.busId;
    }
    
    public void setBusId(Long busId) {
        this.busId = busId;
    }
    public String getBusName() {
        return this.busName;
    }
    
    public void setBusName(String busName) {
        this.busName = busName;
    }
    public String getRoute() {
        return this.route;
    }
    
    public void setRoute(String route) {
        this.route = route;
    }
    public String getBusFrom() {
        return this.busFrom;
    }
    
    public void setBusFrom(String busFrom) {
        this.busFrom = busFrom;
    }
    public String getBusTo() {
        return this.busTo;
    }
    
    public void setBusTo(String busTo) {
        this.busTo = busTo;
    }
    public Time getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Time startTime) {
        this.startTime = startTime;
    }
    public Time getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Time endTime) {
        this.endTime = endTime;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Long getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedAt() {
        return this.modifiedAt;
    }
    
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }
    public Set getBusInfos() {
        return this.busInfos;
    }
    
    public void setBusInfos(Set busInfos) {
        this.busInfos = busInfos;
    }
    public Set getBookingsDatas() {
        return this.bookingsDatas;
    }
    
    public void setBookingsDatas(Set bookingsDatas) {
        this.bookingsDatas = bookingsDatas;
    }
    public Set getBoardingPoints() {
        return this.boardingPoints;
    }
    
    public void setBoardingPoints(Set boardingPoints) {
        this.boardingPoints = boardingPoints;
    }
    public Set getDroppingPoints() {
        return this.droppingPoints;
    }
    
    public void setDroppingPoints(Set droppingPoints) {
        this.droppingPoints = droppingPoints;
    }
    public Set getBusesImages() {
        return this.busesImages;
    }
    
    public void setBusesImages(Set busesImages) {
        this.busesImages = busesImages;
    }




}


