package com.redbus.bean.pojo;
// Generated Jun 22, 2024 7:50:33 PM by Hibernate Tools 3.4.0.CR1


import java.sql.Date;
import java.sql.Timestamp;

/**
 * BusesImage generated by hbm2java
 */
public class BusesImage  implements java.io.Serializable {


     private Long id;
     private String imagePath;
     private String isActive;
     private Long modifiedBy;
     private Date modifiedAt;
     private Long createdBy;
     private Timestamp createdAt;
     private Bus bus;

    public BusesImage() {
    }

	
    public BusesImage(String imagePath, String isActive, Long createdBy, Timestamp createdAt) {
        this.imagePath = imagePath;
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }
    public BusesImage(String imagePath, String isActive, Long modifiedBy, Date modifiedAt, Long createdBy, Timestamp createdAt, Bus bus) {
       this.imagePath = imagePath;
       this.isActive = isActive;
       this.modifiedBy = modifiedBy;
       this.modifiedAt = modifiedAt;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.bus = bus;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Long getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedAt() {
        return this.modifiedAt;
    }
    
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }




}


