package com.redbus.bean.pojo;
// Generated Jun 22, 2024 7:50:33 PM by Hibernate Tools 3.4.0.CR1


import java.sql.Date;
import java.sql.Timestamp;

/**
 * BusInfo generated by hbm2java
 */
public class BusInfo  implements java.io.Serializable {


     private Long id;
     private Integer busType;
     private String busRegistationNumber;
     private String isPrimo;
     private Integer ticketPrice;
     private Integer totalSeats;
     private String isActive;
     private Long modifiedBy;
     private Date modifiedAt;
     private Long createdBy;
     private Timestamp createdAt;
     private Bus bus;

    public BusInfo() {
    }

	
    public BusInfo(Integer busType, String busRegistationNumber, String isPrimo, Integer ticketPrice, Integer totalSeats, String isActive, Timestamp createdAt) {
        this.busType = busType;
        this.busRegistationNumber = busRegistationNumber;
        this.isPrimo = isPrimo;
        this.ticketPrice = ticketPrice;
        this.totalSeats = totalSeats;
        this.isActive = isActive;
        this.createdAt = createdAt;
    }
    public BusInfo(Integer busType, String busRegistationNumber, String isPrimo, Integer ticketPrice, Integer totalSeats, String isActive, Long modifiedBy, Date modifiedAt, Long createdBy, Timestamp createdAt, Bus bus) {
       this.busType = busType;
       this.busRegistationNumber = busRegistationNumber;
       this.isPrimo = isPrimo;
       this.ticketPrice = ticketPrice;
       this.totalSeats = totalSeats;
       this.isActive = isActive;
       this.modifiedBy = modifiedBy;
       this.modifiedAt = modifiedAt;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.bus = bus;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Integer getBusType() {
        return this.busType;
    }
    
    public void setBusType(Integer busType) {
        this.busType = busType;
    }
    public String getBusRegistationNumber() {
        return this.busRegistationNumber;
    }
    
    public void setBusRegistationNumber(String busRegistationNumber) {
        this.busRegistationNumber = busRegistationNumber;
    }
    public String getIsPrimo() {
        return this.isPrimo;
    }
    
    public void setIsPrimo(String isPrimo) {
        this.isPrimo = isPrimo;
    }
    public Integer getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(Integer ticketPrice) {
        this.ticketPrice = ticketPrice;
    }
    public Integer getTotalSeats() {
        return this.totalSeats;
    }
    
    public void setTotalSeats(Integer totalSeats) {
        this.totalSeats = totalSeats;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Long getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedAt() {
        return this.modifiedAt;
    }
    
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }




}


