package com.redbus.bean.pojo;
// Generated Jun 22, 2024 7:50:33 PM by Hibernate Tools 3.4.0.CR1


import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long userId;
     private Integer userType;
     private Long mobileNumber;
     private String email;
     private String name;
     private String userProfile;
     private String gender;
     private String cpassword;
     private String isActive;
     private Long modifiedBy;
     private Date modifiedAt;
     private Long createdBy;
     private Timestamp createdAt;
     private Set bookingsDatas = new HashSet(0);

    public User() {
    }

	
    public User(Long mobileNumber, String email, String name, String cpassword, Timestamp createdAt) {
        this.mobileNumber = mobileNumber;
        this.email = email;
        this.name = name;
        this.cpassword = cpassword;
        this.createdAt = createdAt;
    }
    public User(Integer userType, Long mobileNumber, String email, String name, String userProfile, String gender, String cpassword, String isActive, Long modifiedBy, Date modifiedAt, Long createdBy, Timestamp createdAt, Set bookingsDatas) {
       this.userType = userType;
       this.mobileNumber = mobileNumber;
       this.email = email;
       this.name = name;
       this.userProfile = userProfile;
       this.gender = gender;
       this.cpassword = cpassword;
       this.isActive = isActive;
       this.modifiedBy = modifiedBy;
       this.modifiedAt = modifiedAt;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.bookingsDatas = bookingsDatas;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public Integer getUserType() {
        return this.userType;
    }
    
    public void setUserType(Integer userType) {
        this.userType = userType;
    }
    public Long getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(Long mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUserProfile() {
        return this.userProfile;
    }
    
    public void setUserProfile(String userProfile) {
        this.userProfile = userProfile;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getCpassword() {
        return this.cpassword;
    }
    
    public void setCpassword(String cpassword) {
        this.cpassword = cpassword;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Long getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedAt() {
        return this.modifiedAt;
    }
    
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }
    public Set getBookingsDatas() {
        return this.bookingsDatas;
    }
    
    public void setBookingsDatas(Set bookingsDatas) {
        this.bookingsDatas = bookingsDatas;
    }




}


